version: "3.8"

services:
  # MongoDB Service
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: surya4
  
  # Mongo-Express Service
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: surya4
      ME_CONFIG_MONGODB_URL: mongodb://admin:surya4@mongodb:27017/

  # Node.js Application Service 
  app:
    build: .
    container_name: sg-university-app
    ports:
      - "5050:5050"
    environment:
      - MONGO_URL=mongodb://admin:surya4@mongodb:27017/